'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.42
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Datos
Imports WWTS.General.Reglas


Public Class ConfigSiembra

#Region "Campos constantes"
  Private Const _Procedimiento As String = "proc_ConfigSiembra"
#End Region

#Region "Campos variables"
#End Region

#Region "Propiedades públicas de la clase"
#End Region

#Region "Constructores de la clase"
  Public Sub New(ByVal _OperadorDatos As OperadorDatos)
    If _OperadorDatos Is Nothing Then
      Throw New InvalidOperationException("El operador de datos es nulo")
    End If

    OperadorDatos = _OperadorDatos
    EsNuevo = False
    If Not esNuevo Then
      If Not Me.Recargar Then
        esNuevo = True
        'Throw New Exception("El objeto no puede ser cargado")
      End If
    End If
  End Sub
#End Region

#Region "Implementación de los métodos de persistencia"
  Public Function Recargar() As Boolean
    Dim dsResult As New DataSet
    Dim bResult As Boolean

    With OperadorDatos
      .AgregarParametro("@accion", "C")
      .Procedimiento = _Procedimiento
      bResult = .Ejecutar(dsResult)
      .LimpiarParametros()
    End With
    If bResult AndAlso Not dsResult Is Nothing AndAlso dsResult.Tables.Count > 0 AndAlso dsResult.Tables(0).Rows.Count > 0 Then
      Me.MapearDataRowaObjeto(dsResult.Tables(0).Rows(0))
      Return True
    Else
      Return False
    End If
  End Function
#End Region

#Region "Métodos internos de la clase"
  Private Sub MapearDataRowaObjeto(ByVal Fila As DataRow)
    Me.mCfs_empaque = CInt(Fila("Cfs_empaque"))
    Me.mCfs_ensarte = CInt(Fila("Cfs_ensarte"))
    Me.mCfs_tara = CDec(Fila("Cfs_tara"))
    Me.mCfs_rutaetiq = CStr(Fila("Cfs_rutaetiq"))
    Me.mCfs_bloque = CStr(Fila("Cfs_bloque"))
  End Sub

  Public Function Guardar() As Boolean
    Dim dsResult As New DataSet
    Dim bReturn As Boolean
    Dim sAccion As String = String.Empty
    If esNuevo Then
      sAccion = "I"
    Else
      sAccion = "M"
    End If
    With OperadorDatos
      .AgregarParametro("@accion", sAccion)
      .AgregarParametro("@Cfs_empaque", Me.mCfs_empaque)
      .AgregarParametro("@Cfs_ensarte", Me.mCfs_ensarte)
      .AgregarParametro("@Cfs_rutaetiq", Me.mCfs_rutaetiq)
      .AgregarParametro("@Cfs_tara", Me.mCfs_tara)
      .AgregarParametro("@Cfs_bloque", Me.mCfs_bloque)
      .Procedimiento = _Procedimiento
      bReturn = .Ejecutar(dsResult)
      If bReturn Then
        EsNuevo = False
      End If
      .LimpiarParametros()
    End With
    Return bReturn
  End Function

  Private Function Eliminar() As Boolean
    Return False
  End Function

  Public Function AvanzarEmpaque() As Boolean
    Me.mCfs_empaque += 1
    Return Guardar()
  End Function
  Public Function AvanzarEnsarte() As Boolean
    Me.mCfs_ensarte += 1
    Return Guardar()
  End Function
  Public Function AvanzarBloque() As Boolean
    Me.mCfs_bloque += 1
    Return Guardar()
  End Function
#End Region

#Region "Métodos compartidos"
#End Region
End Class