'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.42
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "BodegaTerreno"
Partial Public Class BodegaTerreno
  Inherits _Database

#Region "Campos variables"
  Private mBod_codigo As String = String.Empty
  Private mBod_nombre As String = String.Empty
  Private mBod_ubicacion As String = String.Empty
  Private mTrr_codigo As String = String.Empty
#End Region

#Region "Propiedades públicas de la clase"
  <XmlAttribute()> _
  Public Overridable Property Bod_codigo() As String
    Get
      Return Me.mBod_codigo
    End Get
    Set(ByVal value As String)
      If String.IsNullOrWhiteSpace(value) Then
        Throw New ArgumentNullException("Código", "El código no acepta vacio")
      End If

      If value.Trim.Length > 5 Then
        Throw New ArgumentException("Código", "El código debe tener hasta 5 caracteres")
      End If
      Me.mBod_codigo = value
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Bod_nombre() As String
    Get
      Return Me.mBod_nombre
    End Get
    Set(ByVal Value As String)
      If String.IsNullOrWhiteSpace(Value) Then
        Throw New ArgumentNullException("Descripcion", "La Descripcion no acepta vacio")
      End If
      mBod_nombre = Value
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Bod_ubicacion() As String
    Get
      Return Me.mBod_ubicacion
    End Get
    Set(ByVal Value As String)
      If String.IsNullOrWhiteSpace(Value) Then
        Throw New ArgumentNullException("Ubicación", "La ubicación no acepta vacio")
      End If
      mBod_ubicacion = Value
    End Set
  End Property
#End Region

#Region "Constructores de la clase"
  Public Sub New()
    MyBase.New()
  End Sub
#End Region
End Class
#End Region