'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.42
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "ClaseHoja"
Partial Public Class ClaseHoja
  Inherits _Database

#Region "Campos variables"
  Private mCla_codigo As String = String.Empty
  Private mCla_codigoAux As String = String.Empty
  Private mCla_nombre As String = String.Empty
  Private mCla_orden As String = String.Empty
  Private mCla_precio As Double
#End Region

#Region "Propiedades públicas de la clase"
  <XmlAttribute()> _
  Public Overridable Property Cla_codigo() As String
    Get
      Return Me.mCla_codigo
    End Get
    Set(ByVal value As String)
      If String.IsNullOrWhiteSpace(value) Then
        Throw New ArgumentNullException("Código", "El código no acepta vacio")
      End If
      Me.mCla_codigo = value
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Cla_codigoAux() As String
    Get
      Return Me.mCla_codigoAux
    End Get
    Set(ByVal value As String)
      If String.IsNullOrWhiteSpace(value) Then
        Throw New ArgumentNullException("Código", "El código no acepta vacio")
      End If
      Me.mCla_codigoAux = value
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Cla_Orden() As String
    Get
      Return Me.mCla_orden
    End Get
    Set(ByVal value As String)
      If String.IsNullOrWhiteSpace(value) Then
        Throw New ArgumentNullException("Orden", "El código no acepta vacio")
      End If
      Me.mCla_orden = value
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Cla_precio() As Double
    Get
      Return Me.mCla_precio
    End Get
    Set(ByVal value As Double)
      If value < 0 Then
        Throw New ArgumentNullException("Precio", "El código no puede ser nulo")
      End If
      Me.mCla_precio = value
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Cla_nombre() As String
    Get
      Return Me.mCla_nombre
    End Get
    Set(ByVal Value As String)
      If String.IsNullOrWhiteSpace(Value) Then
        Throw New ArgumentNullException("Descripcion", "La Descripcion no acepta vacio")
      End If
      mCla_nombre = Value
    End Set
  End Property
#End Region

#Region "Constructores de la clase"
  Public Sub New()
    MyBase.New()
  End Sub
#End Region
End Class
#End Region