'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.42
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "ColorHoja"
Partial Public Class ColorHoja
  Inherits _Database

#Region "Campos variables"
  Private mCol_codigo As String = String.Empty
  Private mCol_nombre As String = String.Empty
  Private mCol_orden As Integer = 0
#End Region

#Region "Propiedades públicas de la clase"
  <XmlAttribute()> _
  Public Overridable Property Col_codigo() As String
    Get
      Return Me.mCol_codigo
    End Get
    Set(ByVal value As String)
      If String.IsNullOrWhiteSpace(value) Then
        Throw New ArgumentNullException("Código", "El código no acepta vacio")
      End If

      If value.Trim.Length > 30 Then
        Throw New ArgumentException("Código", "El código debe tener hasta 5 caracteres")
      End If
      Me.mCol_codigo = value
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Col_nombre() As String
    Get
      Return Me.mCol_nombre
    End Get
    Set(ByVal Value As String)
      If String.IsNullOrWhiteSpace(Value) Then
        Throw New ArgumentNullException("Descripcion", "La Descripcion no acepta vacio")
      End If
      mCol_nombre = Value
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Col_orden() As Integer
    Get
      Return mCol_orden
    End Get
    Set(ByVal Value As Integer)
      mCol_orden = Value
    End Set
  End Property
#End Region

#Region "Constructores de la clase"
  Public Sub New()
    MyBase.New()
  End Sub
#End Region
End Class
#End Region