'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.42
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "Curacion"
Partial Public Class Curacion
    Inherits _Database

#Region "Campos variables"
    Private mCur_numero As Integer = 0
    Private mZaf_codigo As String = String.Empty
    Private mCur_fecha As Date = Now.Date
    Private mHor_codigo As String = String.Empty
    Private mSec_codigo As Integer = 0
    Private mSem_codigo As String = String.Empty
    Private mTrr_codigo As String = String.Empty
    Private mLot_codigo As Integer = 0
    Private mCur_fechaingreso As Date = Nothing
    Private mParame_TipoTabaco As Integer = 0
    Private mPardet_TipoTabaco As Integer = 0

#End Region

#Region "Propiedades públicas de la clase"

    <XmlAttribute()>
    Public Overridable Property Cur_numero() As Integer
        Get
            Return mCur_numero
        End Get
        Set(ByVal Value As Integer)
            mCur_numero = Value
        End Set
    End Property

    <XmlAttribute()>
    Public Overridable Property Cur_fecha() As Date
        Get
            Return mCur_fecha
        End Get
        Set(ByVal Value As Date)
            mCur_fecha = Value
        End Set
    End Property

    <XmlAttribute()>
    Public Overridable Property Cur_fechaingreso() As Date
        Get
            Return mCur_fechaingreso
        End Get
        Set(ByVal Value As Date)
            mCur_fechaingreso = Value
        End Set
    End Property

    <XmlAttribute()>
    Public Overridable Property Parame_TipoTabaco As Integer
        Get
            Return mParame_TipoTabaco
        End Get
        Set(value As Integer)
            mParame_TipoTabaco = value
        End Set
    End Property

    <XmlAttribute()>
    Public Overridable Property Pardet_TipoTabaco As Integer
        Get
            Return mPardet_TipoTabaco
        End Get
        Set(value As Integer)
            mPardet_TipoTabaco = value
        End Set
    End Property
#End Region

#Region "Constructores de la clase"
    Public Sub New()
        MyBase.New()
    End Sub
#End Region
End Class
#End Region