'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.42
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "Embarque"
Partial Public Class Embarque
  Inherits _Database

#Region "Campos variables"
  Private mZaf_codigo As String = String.Empty
  Private mEmb_codigo As Integer = 0
  Private mEmb_fecha As DateTime = Nothing
  Private mDes_codigo As Integer = 0
#End Region

#Region "Propiedades públicas de la clase"

  <XmlAttribute()> _
  Public Overridable Property Emb_codigo() As Integer
    Get
      Return Me.mEmb_codigo
    End Get
    Set(ByVal value As Integer)
      If value <= 0 Then
        Throw New ArgumentNullException("Código", "El código no puede ser nulo")
      End If
      Me.mEmb_codigo = value
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emb_fecha() As DateTime
    Get
      Return Me.mEmb_fecha
    End Get
    Set(ByVal Value As DateTime)
      If Value = Nothing Then
        Throw New ArgumentNullException("Fecha de embarque", "La fecha de embarque no puede ser nula")
      End If
      mEmb_fecha = Value
    End Set
  End Property
#End Region

#Region "Constructores de la clase"
  Public Sub New()
    MyBase.New()
  End Sub
#End Region
End Class
#End Region