'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.42
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "SeccionHorno"
Partial Public Class SeccionHorno
  Inherits _Database

#Region "Campos variables"
  Private mHor_codigo As String = String.Empty
  Private mSec_codigo As Integer = 0
#End Region
#Region "Propiedades públicas de la clase"

  <XmlAttribute()> _
  Public Overridable Property Sec_codigo() As Integer
    Get
      Return Me.mSec_codigo
    End Get
    Set(ByVal value As Integer)
      If value = 0 Then
        Throw New ArgumentNullException("Código", "El código no puede ser nulo")
      End If
      Me.mSec_codigo = value
    End Set
  End Property
#End Region

#Region "Constructores de la clase"
  Public Sub New()
    MyBase.New()
  End Sub
#End Region
End Class
#End Region