'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.42
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "Terreno"
Partial Public Class Terreno
  Inherits _Database
#Region "Campos variables"
  Private mTrr_codigo As String = String.Empty
  Private mTrr_nombre As String = String.Empty
  Private mPro_codigo As String = String.Empty
  Private mhac_codigo As String = String.Empty
  Private mtrr_areaT As Double
  Private mtrr_areaU As Double
#End Region
#Region "Propiedades públicas de la clase"
  <XmlAttribute()> _
  Public Overridable Property Hac_codigo() As String
    Get
      Return Me.mhac_codigo
    End Get
    Set(ByVal value As String)
      If String.IsNullOrWhiteSpace(value) Then
        Throw New ArgumentNullException("Código", "El código no acepta vacio")
      End If

      If value.Trim.Length > 5 Then
        Throw New ArgumentException("Código", "El código debe tener hasta 5 caracteres")
      End If
      Me.mhac_codigo = value
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Trr_codigo() As String
    Get
      Return Me.mTrr_codigo
    End Get
    Set(ByVal value As String)
      If String.IsNullOrWhiteSpace(value) Then
        Throw New ArgumentNullException("Código", "El código no acepta vacio")
      End If
      Me.mTrr_codigo = value
    End Set
  End Property
  
  <XmlAttribute()> _
  Public Overridable Property Trr_AreaU() As Double
    Get
      Return Me.mtrr_areaU
    End Get
    Set(ByVal Value As Double)
      mtrr_areaU = Value
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Trr_AreaT() As Double
    Get
      Return Me.mtrr_areaT
    End Get
    Set(ByVal Value As Double)
      mtrr_areaT = Value
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Trr_nombre() As String
    Get
      Return Me.mTrr_nombre
    End Get
    Set(ByVal Value As String)
      If String.IsNullOrWhiteSpace(Value) Then
        Throw New ArgumentNullException("Descripcion", "La Descripcion no acepta vacio")
      End If
      mTrr_nombre = Value
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pro_codigo() As String
    Get
      Return Me.mPro_codigo
    End Get
    Set(ByVal Value As String)
      If String.IsNullOrWhiteSpace(Value) Then
        Throw New ArgumentNullException("Propietario", "La Descripcion no acepta vacio")
      End If
      mPro_codigo = Value
    End Set
  End Property
#End Region

#Region "Constructores de la clase"
  Public Sub New()
    MyBase.New()
  End Sub
#End Region
End Class
#End Region