'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DSReciboPago"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DSReciboPago
    Inherits Global.System.Data.DataSet
    
    Private tablev_recibopago As v_recibopagoDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("v_recibopago")) Is Nothing) Then
                MyBase.Tables.Add(New v_recibopagoDataTable(ds.Tables("v_recibopago")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property v_recibopago() As v_recibopagoDataTable
        Get
            Return Me.tablev_recibopago
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DSReciboPago = CType(MyBase.Clone,DSReciboPago)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("v_recibopago")) Is Nothing) Then
                MyBase.Tables.Add(New v_recibopagoDataTable(ds.Tables("v_recibopago")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tablev_recibopago = CType(MyBase.Tables("v_recibopago"),v_recibopagoDataTable)
        If (initTable = true) Then
            If (Not (Me.tablev_recibopago) Is Nothing) Then
                Me.tablev_recibopago.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "DSReciboPago"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DSReciboPago.xsd"
        Me.Locale = New Global.System.Globalization.CultureInfo("es-EC")
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tablev_recibopago = New v_recibopagoDataTable
        MyBase.Tables.Add(Me.tablev_recibopago)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializev_recibopago() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DSReciboPago = New DSReciboPago
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub v_recibopagoRowChangeEventHandler(ByVal sender As Object, ByVal e As v_recibopagoRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class v_recibopagoDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnEntida_Codigo As Global.System.Data.DataColumn
        
        Private columnEntnat_Apellidopaterno As Global.System.Data.DataColumn
        
        Private columnEntnat_Apellidomaterno As Global.System.Data.DataColumn
        
        Private columnEntnat_Nombres As Global.System.Data.DataColumn
        
        Private columnAsiste_diario As Global.System.Data.DataColumn
        
        Private columnAsiste_diasintegrales As Global.System.Data.DataColumn
        
        Private columnAsiste_hlv As Global.System.Data.DataColumn
        
        Private columnAsiste_hsdf As Global.System.Data.DataColumn
        
        Private columnAsiste_htrab As Global.System.Data.DataColumn
        
        Private columnAsiste_smb As Global.System.Data.DataColumn
        
        Private columnAsiste_slv As Global.System.Data.DataColumn
        
        Private columnAsiste_ssdf As Global.System.Data.DataColumn
        
        Private columnAsiste_ics As Global.System.Data.DataColumn
        
        Private columnAsiste_adicionalp As Global.System.Data.DataColumn
        
        Private columnAsiste_transpp As Global.System.Data.DataColumn
        
        Private columnAsiste_iess As Global.System.Data.DataColumn
        
        Private columnAsiste_prestamo As Global.System.Data.DataColumn
        
        Private columnAsiste_prestamoquirog As Global.System.Data.DataColumn
        
        Private columnAsiste_multa As Global.System.Data.DataColumn
        
        Private columnAsiste_sueldopagar As Global.System.Data.DataColumn
        
        Private columnAsiste_impuestorenta As Global.System.Data.DataColumn
        
        Private columnAsiste_d3pag As Global.System.Data.DataColumn
        
        Private columnAsiste_d4pag As Global.System.Data.DataColumn
        
        Private columnAsiste_vacpag As Global.System.Data.DataColumn
        
        Private columnPerPag_fechadesde As Global.System.Data.DataColumn
        
        Private columnPerPag_fechahasta As Global.System.Data.DataColumn
        
        Private columnSeccion As Global.System.Data.DataColumn
        
        Private columnLabor As Global.System.Data.DataColumn
        
        Private columnCedula As Global.System.Data.DataColumn
        
        Private columnPatrono As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "v_recibopago"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Entida_CodigoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEntida_Codigo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Entnat_ApellidopaternoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEntnat_Apellidopaterno
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Entnat_ApellidomaternoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEntnat_Apellidomaterno
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Entnat_NombresColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEntnat_Nombres
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_diarioColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_diario
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_diasintegralesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_diasintegrales
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_hlvColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_hlv
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_hsdfColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_hsdf
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_htrabColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_htrab
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_smbColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_smb
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_slvColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_slv
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_ssdfColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_ssdf
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_icsColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_ics
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_adicionalpColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_adicionalp
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_transppColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_transpp
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_iessColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_iess
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_prestamoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_prestamo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_prestamoquirogColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_prestamoquirog
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_multaColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_multa
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_sueldopagarColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_sueldopagar
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_impuestorentaColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_impuestorenta
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_d3pagColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_d3pag
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_d4pagColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_d4pag
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Asiste_vacpagColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAsiste_vacpag
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PerPag_fechadesdeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPerPag_fechadesde
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PerPag_fechahastaColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPerPag_fechahasta
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SeccionColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSeccion
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property LaborColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnLabor
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CedulaColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCedula
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PatronoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPatrono
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As v_recibopagoRow
            Get
                Return CType(Me.Rows(index),v_recibopagoRow)
            End Get
        End Property
        
        Public Event v_recibopagoRowChanging As v_recibopagoRowChangeEventHandler
        
        Public Event v_recibopagoRowChanged As v_recibopagoRowChangeEventHandler
        
        Public Event v_recibopagoRowDeleting As v_recibopagoRowChangeEventHandler
        
        Public Event v_recibopagoRowDeleted As v_recibopagoRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub Addv_recibopagoRow(ByVal row As v_recibopagoRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function Addv_recibopagoRow( _
                    ByVal Entida_Codigo As Integer,  _
                    ByVal Entnat_Apellidopaterno As String,  _
                    ByVal Entnat_Apellidomaterno As String,  _
                    ByVal Entnat_Nombres As String,  _
                    ByVal Asiste_diario As Decimal,  _
                    ByVal Asiste_diasintegrales As Decimal,  _
                    ByVal Asiste_hlv As Integer,  _
                    ByVal Asiste_hsdf As Integer,  _
                    ByVal Asiste_htrab As Integer,  _
                    ByVal Asiste_smb As Decimal,  _
                    ByVal Asiste_slv As Decimal,  _
                    ByVal Asiste_ssdf As Decimal,  _
                    ByVal Asiste_ics As Decimal,  _
                    ByVal Asiste_adicionalp As Decimal,  _
                    ByVal Asiste_transpp As Decimal,  _
                    ByVal Asiste_iess As Decimal,  _
                    ByVal Asiste_prestamo As Decimal,  _
                    ByVal Asiste_prestamoquirog As Decimal,  _
                    ByVal Asiste_multa As Decimal,  _
                    ByVal Asiste_sueldopagar As Decimal,  _
                    ByVal Asiste_impuestorenta As Decimal,  _
                    ByVal Asiste_d3pag As Decimal,  _
                    ByVal Asiste_d4pag As Decimal,  _
                    ByVal Asiste_vacpag As Decimal,  _
                    ByVal PerPag_fechadesde As Date,  _
                    ByVal PerPag_fechahasta As Date,  _
                    ByVal Seccion As String,  _
                    ByVal Labor As String,  _
                    ByVal Cedula As String,  _
                    ByVal Patrono As String) As v_recibopagoRow
            Dim rowv_recibopagoRow As v_recibopagoRow = CType(Me.NewRow,v_recibopagoRow)
            Dim columnValuesArray() As Object = New Object() {Entida_Codigo, Entnat_Apellidopaterno, Entnat_Apellidomaterno, Entnat_Nombres, Asiste_diario, Asiste_diasintegrales, Asiste_hlv, Asiste_hsdf, Asiste_htrab, Asiste_smb, Asiste_slv, Asiste_ssdf, Asiste_ics, Asiste_adicionalp, Asiste_transpp, Asiste_iess, Asiste_prestamo, Asiste_prestamoquirog, Asiste_multa, Asiste_sueldopagar, Asiste_impuestorenta, Asiste_d3pag, Asiste_d4pag, Asiste_vacpag, PerPag_fechadesde, PerPag_fechahasta, Seccion, Labor, Cedula, Patrono}
            rowv_recibopagoRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowv_recibopagoRow)
            Return rowv_recibopagoRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As v_recibopagoDataTable = CType(MyBase.Clone,v_recibopagoDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New v_recibopagoDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnEntida_Codigo = MyBase.Columns("Entida_Codigo")
            Me.columnEntnat_Apellidopaterno = MyBase.Columns("Entnat_Apellidopaterno")
            Me.columnEntnat_Apellidomaterno = MyBase.Columns("Entnat_Apellidomaterno")
            Me.columnEntnat_Nombres = MyBase.Columns("Entnat_Nombres")
            Me.columnAsiste_diario = MyBase.Columns("Asiste_diario")
            Me.columnAsiste_diasintegrales = MyBase.Columns("Asiste_diasintegrales")
            Me.columnAsiste_hlv = MyBase.Columns("Asiste_hlv")
            Me.columnAsiste_hsdf = MyBase.Columns("Asiste_hsdf")
            Me.columnAsiste_htrab = MyBase.Columns("Asiste_htrab")
            Me.columnAsiste_smb = MyBase.Columns("Asiste_smb")
            Me.columnAsiste_slv = MyBase.Columns("Asiste_slv")
            Me.columnAsiste_ssdf = MyBase.Columns("Asiste_ssdf")
            Me.columnAsiste_ics = MyBase.Columns("Asiste_ics")
            Me.columnAsiste_adicionalp = MyBase.Columns("Asiste_adicionalp")
            Me.columnAsiste_transpp = MyBase.Columns("Asiste_transpp")
            Me.columnAsiste_iess = MyBase.Columns("Asiste_iess")
            Me.columnAsiste_prestamo = MyBase.Columns("Asiste_prestamo")
            Me.columnAsiste_prestamoquirog = MyBase.Columns("Asiste_prestamoquirog")
            Me.columnAsiste_multa = MyBase.Columns("Asiste_multa")
            Me.columnAsiste_sueldopagar = MyBase.Columns("Asiste_sueldopagar")
            Me.columnAsiste_impuestorenta = MyBase.Columns("Asiste_impuestorenta")
            Me.columnAsiste_d3pag = MyBase.Columns("Asiste_d3pag")
            Me.columnAsiste_d4pag = MyBase.Columns("Asiste_d4pag")
            Me.columnAsiste_vacpag = MyBase.Columns("Asiste_vacpag")
            Me.columnPerPag_fechadesde = MyBase.Columns("PerPag_fechadesde")
            Me.columnPerPag_fechahasta = MyBase.Columns("PerPag_fechahasta")
            Me.columnSeccion = MyBase.Columns("Seccion")
            Me.columnLabor = MyBase.Columns("Labor")
            Me.columnCedula = MyBase.Columns("Cedula")
            Me.columnPatrono = MyBase.Columns("Patrono")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnEntida_Codigo = New Global.System.Data.DataColumn("Entida_Codigo", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEntida_Codigo)
            Me.columnEntnat_Apellidopaterno = New Global.System.Data.DataColumn("Entnat_Apellidopaterno", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEntnat_Apellidopaterno)
            Me.columnEntnat_Apellidomaterno = New Global.System.Data.DataColumn("Entnat_Apellidomaterno", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEntnat_Apellidomaterno)
            Me.columnEntnat_Nombres = New Global.System.Data.DataColumn("Entnat_Nombres", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEntnat_Nombres)
            Me.columnAsiste_diario = New Global.System.Data.DataColumn("Asiste_diario", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_diario)
            Me.columnAsiste_diasintegrales = New Global.System.Data.DataColumn("Asiste_diasintegrales", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_diasintegrales)
            Me.columnAsiste_hlv = New Global.System.Data.DataColumn("Asiste_hlv", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_hlv)
            Me.columnAsiste_hsdf = New Global.System.Data.DataColumn("Asiste_hsdf", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_hsdf)
            Me.columnAsiste_htrab = New Global.System.Data.DataColumn("Asiste_htrab", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_htrab)
            Me.columnAsiste_smb = New Global.System.Data.DataColumn("Asiste_smb", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_smb)
            Me.columnAsiste_slv = New Global.System.Data.DataColumn("Asiste_slv", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_slv)
            Me.columnAsiste_ssdf = New Global.System.Data.DataColumn("Asiste_ssdf", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_ssdf)
            Me.columnAsiste_ics = New Global.System.Data.DataColumn("Asiste_ics", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_ics)
            Me.columnAsiste_adicionalp = New Global.System.Data.DataColumn("Asiste_adicionalp", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_adicionalp)
            Me.columnAsiste_transpp = New Global.System.Data.DataColumn("Asiste_transpp", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_transpp)
            Me.columnAsiste_iess = New Global.System.Data.DataColumn("Asiste_iess", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_iess)
            Me.columnAsiste_prestamo = New Global.System.Data.DataColumn("Asiste_prestamo", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_prestamo)
            Me.columnAsiste_prestamoquirog = New Global.System.Data.DataColumn("Asiste_prestamoquirog", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_prestamoquirog)
            Me.columnAsiste_multa = New Global.System.Data.DataColumn("Asiste_multa", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_multa)
            Me.columnAsiste_sueldopagar = New Global.System.Data.DataColumn("Asiste_sueldopagar", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_sueldopagar)
            Me.columnAsiste_impuestorenta = New Global.System.Data.DataColumn("Asiste_impuestorenta", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_impuestorenta)
            Me.columnAsiste_d3pag = New Global.System.Data.DataColumn("Asiste_d3pag", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_d3pag)
            Me.columnAsiste_d4pag = New Global.System.Data.DataColumn("Asiste_d4pag", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_d4pag)
            Me.columnAsiste_vacpag = New Global.System.Data.DataColumn("Asiste_vacpag", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAsiste_vacpag)
            Me.columnPerPag_fechadesde = New Global.System.Data.DataColumn("PerPag_fechadesde", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPerPag_fechadesde)
            Me.columnPerPag_fechahasta = New Global.System.Data.DataColumn("PerPag_fechahasta", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPerPag_fechahasta)
            Me.columnSeccion = New Global.System.Data.DataColumn("Seccion", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSeccion)
            Me.columnLabor = New Global.System.Data.DataColumn("Labor", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnLabor)
            Me.columnCedula = New Global.System.Data.DataColumn("Cedula", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCedula)
            Me.columnPatrono = New Global.System.Data.DataColumn("Patrono", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPatrono)
            Me.columnEntida_Codigo.AllowDBNull = false
            Me.columnEntnat_Apellidopaterno.AllowDBNull = false
            Me.columnEntnat_Apellidopaterno.MaxLength = 50
            Me.columnEntnat_Apellidomaterno.AllowDBNull = false
            Me.columnEntnat_Apellidomaterno.MaxLength = 50
            Me.columnEntnat_Nombres.AllowDBNull = false
            Me.columnEntnat_Nombres.MaxLength = 50
            Me.columnSeccion.AllowDBNull = false
            Me.columnSeccion.MaxLength = 100
            Me.columnLabor.AllowDBNull = false
            Me.columnLabor.MaxLength = 100
            Me.columnCedula.MaxLength = 50
            Me.columnPatrono.AllowDBNull = false
            Me.columnPatrono.MaxLength = 100
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Newv_recibopagoRow() As v_recibopagoRow
            Return CType(Me.NewRow,v_recibopagoRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New v_recibopagoRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(v_recibopagoRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.v_recibopagoRowChangedEvent) Is Nothing) Then
                RaiseEvent v_recibopagoRowChanged(Me, New v_recibopagoRowChangeEvent(CType(e.Row,v_recibopagoRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.v_recibopagoRowChangingEvent) Is Nothing) Then
                RaiseEvent v_recibopagoRowChanging(Me, New v_recibopagoRowChangeEvent(CType(e.Row,v_recibopagoRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.v_recibopagoRowDeletedEvent) Is Nothing) Then
                RaiseEvent v_recibopagoRowDeleted(Me, New v_recibopagoRowChangeEvent(CType(e.Row,v_recibopagoRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.v_recibopagoRowDeletingEvent) Is Nothing) Then
                RaiseEvent v_recibopagoRowDeleting(Me, New v_recibopagoRowChangeEvent(CType(e.Row,v_recibopagoRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Removev_recibopagoRow(ByVal row As v_recibopagoRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As DSReciboPago = New DSReciboPago
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "v_recibopagoDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class v_recibopagoRow
        Inherits Global.System.Data.DataRow
        
        Private tablev_recibopago As v_recibopagoDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tablev_recibopago = CType(Me.Table,v_recibopagoDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Entida_Codigo() As Integer
            Get
                Return CType(Me(Me.tablev_recibopago.Entida_CodigoColumn),Integer)
            End Get
            Set
                Me(Me.tablev_recibopago.Entida_CodigoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Entnat_Apellidopaterno() As String
            Get
                Return CType(Me(Me.tablev_recibopago.Entnat_ApellidopaternoColumn),String)
            End Get
            Set
                Me(Me.tablev_recibopago.Entnat_ApellidopaternoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Entnat_Apellidomaterno() As String
            Get
                Return CType(Me(Me.tablev_recibopago.Entnat_ApellidomaternoColumn),String)
            End Get
            Set
                Me(Me.tablev_recibopago.Entnat_ApellidomaternoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Entnat_Nombres() As String
            Get
                Return CType(Me(Me.tablev_recibopago.Entnat_NombresColumn),String)
            End Get
            Set
                Me(Me.tablev_recibopago.Entnat_NombresColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_diario() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_diarioColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_diario' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_diarioColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_diasintegrales() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_diasintegralesColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_diasintegrales' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_diasintegralesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_hlv() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_hlvColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_hlv' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_hlvColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_hsdf() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_hsdfColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_hsdf' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_hsdfColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_htrab() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_htrabColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_htrab' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_htrabColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_smb() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_smbColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_smb' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_smbColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_slv() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_slvColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_slv' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_slvColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_ssdf() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_ssdfColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_ssdf' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_ssdfColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_ics() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_icsColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_ics' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_icsColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_adicionalp() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_adicionalpColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_adicionalp' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_adicionalpColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_transpp() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_transppColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_transpp' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_transppColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_iess() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_iessColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_iess' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_iessColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_prestamo() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_prestamoColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_prestamo' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_prestamoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_prestamoquirog() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_prestamoquirogColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_prestamoquirog' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_prestamoquirogColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_multa() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_multaColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_multa' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_multaColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_sueldopagar() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_sueldopagarColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_sueldopagar' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_sueldopagarColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_impuestorenta() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_impuestorentaColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_impuestorenta' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_impuestorentaColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_d3pag() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_d3pagColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_d3pag' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_d3pagColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_d4pag() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_d4pagColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_d4pag' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_d4pagColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Asiste_vacpag() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.Asiste_vacpagColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Asiste_vacpag' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.Asiste_vacpagColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PerPag_fechadesde() As Date
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.PerPag_fechadesdeColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PerPag_fechadesde' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.PerPag_fechadesdeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PerPag_fechahasta() As Date
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.PerPag_fechahastaColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PerPag_fechahasta' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.PerPag_fechahastaColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Seccion() As String
            Get
                Return CType(Me(Me.tablev_recibopago.SeccionColumn),String)
            End Get
            Set
                Me(Me.tablev_recibopago.SeccionColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Labor() As String
            Get
                Return CType(Me(Me.tablev_recibopago.LaborColumn),String)
            End Get
            Set
                Me(Me.tablev_recibopago.LaborColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Cedula() As String
            Get
                Try 
                    Return CType(Me(Me.tablev_recibopago.CedulaColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Cedula' in table 'v_recibopago' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablev_recibopago.CedulaColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Patrono() As String
            Get
                Return CType(Me(Me.tablev_recibopago.PatronoColumn),String)
            End Get
            Set
                Me(Me.tablev_recibopago.PatronoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_diarioNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_diarioColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_diarioNull()
            Me(Me.tablev_recibopago.Asiste_diarioColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_diasintegralesNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_diasintegralesColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_diasintegralesNull()
            Me(Me.tablev_recibopago.Asiste_diasintegralesColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_hlvNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_hlvColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_hlvNull()
            Me(Me.tablev_recibopago.Asiste_hlvColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_hsdfNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_hsdfColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_hsdfNull()
            Me(Me.tablev_recibopago.Asiste_hsdfColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_htrabNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_htrabColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_htrabNull()
            Me(Me.tablev_recibopago.Asiste_htrabColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_smbNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_smbColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_smbNull()
            Me(Me.tablev_recibopago.Asiste_smbColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_slvNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_slvColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_slvNull()
            Me(Me.tablev_recibopago.Asiste_slvColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_ssdfNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_ssdfColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_ssdfNull()
            Me(Me.tablev_recibopago.Asiste_ssdfColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_icsNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_icsColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_icsNull()
            Me(Me.tablev_recibopago.Asiste_icsColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_adicionalpNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_adicionalpColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_adicionalpNull()
            Me(Me.tablev_recibopago.Asiste_adicionalpColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_transppNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_transppColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_transppNull()
            Me(Me.tablev_recibopago.Asiste_transppColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_iessNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_iessColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_iessNull()
            Me(Me.tablev_recibopago.Asiste_iessColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_prestamoNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_prestamoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_prestamoNull()
            Me(Me.tablev_recibopago.Asiste_prestamoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_prestamoquirogNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_prestamoquirogColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_prestamoquirogNull()
            Me(Me.tablev_recibopago.Asiste_prestamoquirogColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_multaNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_multaColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_multaNull()
            Me(Me.tablev_recibopago.Asiste_multaColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_sueldopagarNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_sueldopagarColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_sueldopagarNull()
            Me(Me.tablev_recibopago.Asiste_sueldopagarColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_impuestorentaNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_impuestorentaColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_impuestorentaNull()
            Me(Me.tablev_recibopago.Asiste_impuestorentaColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_d3pagNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_d3pagColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_d3pagNull()
            Me(Me.tablev_recibopago.Asiste_d3pagColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_d4pagNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_d4pagColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_d4pagNull()
            Me(Me.tablev_recibopago.Asiste_d4pagColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAsiste_vacpagNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.Asiste_vacpagColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAsiste_vacpagNull()
            Me(Me.tablev_recibopago.Asiste_vacpagColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPerPag_fechadesdeNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.PerPag_fechadesdeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPerPag_fechadesdeNull()
            Me(Me.tablev_recibopago.PerPag_fechadesdeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPerPag_fechahastaNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.PerPag_fechahastaColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPerPag_fechahastaNull()
            Me(Me.tablev_recibopago.PerPag_fechahastaColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCedulaNull() As Boolean
            Return Me.IsNull(Me.tablev_recibopago.CedulaColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCedulaNull()
            Me(Me.tablev_recibopago.CedulaColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class v_recibopagoRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As v_recibopagoRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As v_recibopagoRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As v_recibopagoRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
