'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Reglas
Imports System
Imports System.Xml
Imports System.Xml.Serialization


#Region "AdicSueldo"
Partial Public Class AdicSueldo
  Inherits _Database

  Private mEntida_Codigo As Integer = 0

  Private mPatron_Codigo As Integer = 0

  Private mContra_Secuencia As Integer = 0

  Private mAdiSue_Secuencia As Integer = 0

  Private mAdiSue_Fecha As DateTime = Now.Date

  Private mParame_TipoAdicional As Integer = 0

  Private mPardet_TipoAdicional As Integer = 0

  Private mAdiSue_Valor As Decimal = 0

  Private mAdiSue_enQuincena As Boolean = True

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Entida_Codigo() As Integer
    Get
      Return Me.mEntida_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Patron_Codigo() As Integer
    Get
      Return Me.mPatron_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mPatron_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Contra_Secuencia() As Integer
    Get
      Return Me.mContra_Secuencia
    End Get
    Set(ByVal value As Integer)
      Me.mContra_Secuencia = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property AdiSue_Secuencia() As Integer
    Get
      Return Me.mAdiSue_Secuencia
    End Get
    Set(ByVal value As Integer)
      Me.mAdiSue_Secuencia = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
 Public Overridable Property AdiSue_Fecha() As DateTime
    Get
      Return mAdiSue_Fecha
    End Get
    Set(ByVal value As DateTime)
      mAdiSue_Fecha = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
 Public Overridable Property Parame_TipoAdicional() As Integer
    Get
      Return mParame_TipoAdicional
    End Get
    Set(ByVal value As Integer)
      mParame_TipoAdicional = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
 Public Overridable Property Pardet_TipoAdicional() As Integer
    Get
      Return mPardet_TipoAdicional
    End Get
    Set(ByVal value As Integer)
      mPardet_TipoAdicional = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
 Public Overridable Property AdiSue_Valor() As Decimal
    Get
      Return mAdiSue_Valor
    End Get
    Set(ByVal value As Decimal)
      mAdiSue_Valor = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
 Public Overridable Property AdiSue_enQuincena() As Boolean
    Get
      Return mAdiSue_enQuincena
    End Get
    Set(ByVal value As Boolean)
      mAdiSue_enQuincena = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region