'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Reglas
Imports System
Imports System.Xml
Imports System.Xml.Serialization


#Region "Provision"
Partial Public Class Provision
  Inherits _Database

  Private mProvis_Secuencia As Integer = 0

  Private mProvis_Observacion As String = ""

  Private mProvis_Fecha As Date = Now.Date

  Private mProvis_Valor As Decimal = 0

  Private mPatron_Codigo As Integer = 0

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Patron_Codigo() As Integer
    Get
      Return Me.mPatron_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mPatron_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Provis_Secuencia() As Integer
    Get
      Return Me.mProvis_Secuencia
    End Get
    Set(value As Integer)
      Me.mProvis_Secuencia = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  <Infoware.Reportes.CampoReporteAtributo("Observación", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Texto, 250, True)> _
  Public Overridable Property Provis_Observacion() As String
    Get
      Return Me.mProvis_Observacion
    End Get
    Set(value As String)
      Me.mProvis_Observacion = value
      EsModificado = True
    End Set
  End Property
  
  <XmlAttribute()> _
  <Infoware.Reportes.CampoReporteAtributo("Fecha", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Fecha, 100, True)> _
  Public Overridable Property Provis_Fecha() As Date
    Get
      Return Me.mProvis_Fecha
    End Get
    Set(value As Date)
      Me.mProvis_Fecha = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  <Infoware.Reportes.CampoReporteAtributo("Valor", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Decimales, 70, True)> _
  Public Overridable Property Provis_Valor() As Decimal
    Get
      Return Me.mProvis_Valor
    End Get
    Set(value As Decimal)
      Me.mProvis_Valor = value
      EsModificado = True
    End Set
  End Property
  
End Class
#End Region
