'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas


#Region "ChequeDetalle"
Partial Public Class ChequeDetalle
  Inherits _Database

  Private mEmpres_Codigo As Integer = 0

  Private mParame_Banco As Integer = 0

  Private mPardet_Banco As Integer = 0

  Private mCtaBan_Numero As Integer = 0

  Private mCheque_Numero As Integer = 0

  Private mParame_Tipomovinv As Integer = 440

  Private mPardet_Tipomovinv As Integer = 1

  Private mEmpres_Bodega As Integer = 0

  Private mSucurs_Bodega As Integer = 0

  Private mMovinv_Secuencia As Integer = 0

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Empres_Codigo() As Integer
    Get
      Return mEmpres_Codigo
    End Get
    Set(ByVal value As Integer)
      mEmpres_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Banco() As Integer
    Get
      Return mParame_Banco
    End Get
    Set(ByVal value As Integer)
      mParame_Banco = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Banco() As Integer
    Get
      Return mPardet_Banco
    End Get
    Set(ByVal value As Integer)
      mPardet_Banco = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property CtaBan_Numero() As Integer
    Get
      Return mCtaBan_Numero
    End Get
    Set(ByVal value As Integer)
      mCtaBan_Numero = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Cheque_Numero() As Integer
    Get
      Return mCheque_Numero
    End Get
    Set(ByVal value As Integer)
      mCheque_Numero = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Tipomovinv() As Integer
    Get
      Return Me.mParame_Tipomovinv
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Tipomovinv = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Tipomovinv() As Integer
    Get
      Return Me.mPardet_Tipomovinv
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Tipomovinv = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Empres_Bodega() As Integer
    Get
      Return Me.mEmpres_Bodega
    End Get
    Set(ByVal value As Integer)
      Me.mEmpres_Bodega = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Sucurs_Bodega() As Integer
    Get
      Return Me.mSucurs_Bodega
    End Get
    Set(ByVal value As Integer)
      Me.mSucurs_Bodega = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Movinv_Secuencia() As Integer
    Get
      Return Me.mMovinv_Secuencia
    End Get
    Set(ByVal value As Integer)
      Me.mMovinv_Secuencia = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region
