'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas

#Region "CuentaContable"
Partial Public Class CuentaContable
  Inherits _Database

  Private mCtaCtb_Codigo As String = ""

  Private mCtaCtb_Descripcion As String = ""

  Private mParame_TipoCtaCtble As Integer = 0

  Private mPardet_TipoCtaCtble As Integer = 0

  Private mCtaCtb_EsGrupo As Boolean = True

  Private mCtaCtb_Nivel As Integer = 0

  Private mCtaCtb_Padre As String = ""

  Private mCtaCtb_Dif As String = ""

  Public Sub New()
    MyBase.New()
  End Sub

  <Infoware.Reportes.CampoReporteAtributo("Código de cuenta", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Texto, 100, True)> _
  <XmlAttribute()> _
  Public Overridable Property CtaCtb_Codigo() As String
    Get
      Return Me.mCtaCtb_Codigo
    End Get
    Set(ByVal value As String)
      Me.mCtaCtb_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property CtaCtb_Descripcion() As String
    Get
      Return Me.mCtaCtb_Descripcion
    End Get
    Set(ByVal value As String)
      Me.mCtaCtb_Descripcion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_TipoCtaCtble() As Integer
    Get
      Return Me.mParame_TipoCtaCtble
    End Get
    Set(ByVal value As Integer)
      Me.mParame_TipoCtaCtble = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_TipoCtaCtble() As Integer
    Get
      Return Me.mPardet_TipoCtaCtble
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_TipoCtaCtble = value
      EsModificado = True
    End Set
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Grupo", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Logico, 50, True)> _
  <XmlAttribute()> _
  Public Overridable Property CtaCtb_EsGrupo() As Boolean
    Get
      Return Me.mCtaCtb_EsGrupo
    End Get
    Set(ByVal value As Boolean)
      Me.mCtaCtb_EsGrupo = value
      EsModificado = True
    End Set
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Nivel", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Numero, 50, True)> _
  <XmlAttribute()> _
  Public Overridable Property CtaCtb_Nivel() As Integer
    Get
      Return Me.mCtaCtb_Nivel
    End Get
    Set(ByVal value As Integer)
      Me.mCtaCtb_Nivel = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property CtaCtb_Padre() As String
    Get
      Return Me.mCtaCtb_Padre
    End Get
    Set(ByVal value As String)
      Me.mCtaCtb_Padre = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property CtaCtb_Dif() As String
    Get
      Return Me.mCtaCtb_Dif
    End Get
    Set(ByVal value As String)
      Me.mCtaCtb_Dif = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region

