'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "Patrono"
Partial Public Class Patrono
  Inherits _Database

  Private mPatron_Codigo As Integer = 0

  Private mEntida_Patrono As Integer = 0

  Private mParame_Parroquia As Integer = 0

  Private mPardet_Parroquia As Integer = 0

  Private mPatron_NumeroPatronal As String = ""

  Private mPatron_NumeroCuentaBancaria As String = ""

  Private mPatron_CodigoContable As String = ""

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Patron_Codigo() As Integer
    Get
      Return Me.mPatron_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mPatron_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entida_Patrono() As Integer
    Get
      Return Me.mEntida_Patrono
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_Patrono = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Parroquia() As Integer
    Get
      Return Me.mParame_Parroquia
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Parroquia = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Parroquia() As Integer
    Get
      Return Me.mPardet_Parroquia
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Parroquia = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Patron_NumeroPatronal() As String
    Get
      Return Me.mPatron_NumeroPatronal
    End Get
    Set(ByVal value As String)
      Me.mPatron_NumeroPatronal = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Patron_NumeroCuentaBancaria() As String
    Get
      Return Me.mPatron_NumeroCuentaBancaria
    End Get
    Set(ByVal value As String)
      Me.mPatron_NumeroCuentaBancaria = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Patron_CodigoContable() As String
    Get
      Return Me.mPatron_CodigoContable
    End Get
    Set(ByVal value As String)
      Me.mPatron_CodigoContable = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region

