'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Reglas
Imports System
Imports System.Xml
Imports System.Xml.Serialization


#Region "PeriodoPago"
Partial Public Class PeriodoPago
  Inherits _Database

  Private mPerPag_FechaDesde As Date = Now.Date

  Private mParame_PeriodoPago As Integer = 0

  Private mPardet_PeriodoPago As Integer = 0

  Private mPerPag_FechaHasta As Date = Now.Date

  Private mPerPag_FechaPago As Date = Now.Date

  Private mPerPag_esPagado As Boolean = False

  Private mPerPag_esQuincena As Boolean = False

  Private mPerPag_anio As Integer = Now.Year

  Private mPerPag_mes As Integer = Now.Month

  Private mPerPag_FechaDesdeMarcacion As Date = Now.Date

  Private mPerPag_FechaHastaMarcacion As Date = Now.Date

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property PerPag_FechaDesde() As Date
    Get
      Return Me.mPerPag_FechaDesde
    End Get
    Set(ByVal value As Date)
      Me.mPerPag_FechaDesde = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_PeriodoPago() As Integer
    Get
      Return Me.mParame_PeriodoPago
    End Get
    Set(ByVal value As Integer)
      Me.mParame_PeriodoPago = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_PeriodoPago() As Integer
    Get
      Return Me.mPardet_PeriodoPago
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_PeriodoPago = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property PerPag_FechaHasta() As Date
    Get
      Return Me.mPerPag_FechaHasta
    End Get
    Set(ByVal value As Date)
      Me.mPerPag_FechaHasta = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property PerPag_FechaPago() As Date
    Get
      Return Me.mPerPag_FechaPago
    End Get
    Set(ByVal value As Date)
      Me.mPerPag_FechaPago = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property PerPag_esPagado() As Boolean
    Get
      Return Me.mPerPag_esPagado
    End Get
    Set(ByVal value As Boolean)
      Me.mPerPag_esPagado = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property PerPag_esQuincena() As Boolean
    Get
      Return Me.mPerPag_esQuincena
    End Get
    Set(ByVal value As Boolean)
      Me.mPerPag_esQuincena = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property PerPag_anio() As Integer
    Get
      Return Me.mPerPag_anio
    End Get
    Set(ByVal value As Integer)
      Me.mPerPag_anio = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property PerPag_mes() As Integer
    Get
      Return Me.mPerPag_mes
    End Get
    Set(ByVal value As Integer)
      If value < 0 Or value > 12 Then
        Throw New Exception("El mes debe tener un valor válido")
      End If
      Me.mPerPag_mes = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property PerPag_FechaDesdeMarcacion() As Date
    Get
      Return Me.mPerPag_FechaDesdeMarcacion
    End Get
    Set(ByVal value As Date)
      Me.mPerPag_FechaDesdeMarcacion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property PerPag_FechaHastaMarcacion() As Date
    Get
      Return Me.mPerPag_FechaHastaMarcacion
    End Get
    Set(ByVal value As Date)
      Me.mPerPag_FechaHastaMarcacion = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region
