'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "RegistroContable"
Partial Public Class RegistroContable
  Inherits _Database

  Private mRegCtb_Secuencia As Integer = 0

  Private mRegCtb_Anio As Integer = 0

  Private mRegCtb_Descripcion As String = ""

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property RegCtb_Secuencia() As Integer
    Get
      Return Me.mRegCtb_Secuencia
    End Get
    Set(ByVal value As Integer)
      Me.mRegCtb_Secuencia = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property RegCtb_Anio() As Integer
    Get
      Return Me.mRegCtb_Anio
    End Get
    Set(ByVal value As Integer)
      Me.mRegCtb_Anio = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property RegCtb_Descripcion() As String
    Get
      Return Me.mRegCtb_Descripcion
    End Get
    Set(ByVal value As String)
      Me.mRegCtb_Descripcion = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region

